stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/

build:
  stage: build
  image: gradle:9.4.0-jdk21
  script:
    - gradle clean compileJava

test:
  stage: test
  image: gradle:9.4.0-jdk21
  script:
    - gradle test
